plugins {
    id 'java-library'
}

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-annotations"
    implementation "jakarta.persistence:jakarta.persistence-api:${rootProject.ext.jakartaPersistenceVersion}"
    compileOnly "org.springdoc:springdoc-openapi-starter-common:${rootProject.ext.springdocVersion}"
}
