plugins {
    id 'java'
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    implementation project(':model')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.7'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.7'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.7'
    implementation "io.minio:minio:${rootProject.ext.minioVersion}"
    implementation "commons-codec:commons-codec:${rootProject.ext.commonsCodecVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${rootProject.ext.springdocVersion}"
}
